routes/web.php
<?php


    Route::get('/', 'Frontend@index');
    Route::redirect('/home', '/admin');

    Auth::routes(['register' => false]);

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');

    Route::delete('blogs/destroy', 'BlogController@massDestroy')->name('blogs.massDestroy');

    Route::resource('blogs', 'BlogController');
    
    
    Route::delete('services/destroy', 'ServiceController@massDestroy')->name('services.massDestroy');

    Route::resource('services', 'ServiceController');
    
    
    Route::delete('projects/destroy', 'projectsController@massDestroy')->name('projects.massDestroy');

    Route::resource('projects', 'projectsController');





    Route::delete('faqs/destroy', 'faqController@massDestroy')->name('faqs.massDestroy');

    Route::resource('faqs', 'faqController');
    
    Route::delete('abouts/destroy', 'AboutController@massDestroy')->name('abouts.massDestroy');
    Route::resource('abouts', 'AboutController');
    
    Route::delete('phases/destroy', 'phasesController@massDestroy')->name('phases.massDestroy');
    Route::resource('phases', 'phasesController');
    
    Route::delete('contactus/destroy', 'ContactUsController@massDestroy')->name('contactuses.massDestroy');
    Route::resource('contactus', 'ContactUsController');
    
    Route::delete('settings/destroy', 'settingController@massDestroy')->name('settings.massDestroy');
    Route::resource('settings', 'settingController');


});

    Route::get('about', 'Frontend@about')->name('about');
    Route::get('blog', 'Frontend@blog')->name('blog');
    Route::get('blog-list/{id}', 'Frontend@blog_list');
    Route::get('contact', 'Frontend@contact');
    Route::get('faq', 'Frontend@faq');   
    Route::post('faq','Frontend@faqs')->name('fs');
    Route::get('service-details/{id}', 'Frontend@service_detail');
    Route::get('service', 'Frontend@service');

    Route::get('projects', 'Frontend@projects');

    Route::get('phases', 'phasesController@index')->name('phases');
    Route::get('setting', 'Frontend@setting')->name('phases');
    Route::post('mail', 'Frontend@cont')->name('mail');
    Route::get('mail', 'Frontend@contactReturn');
    Route::get('details', 'detailscontroller@index');

Route::post('getall', 'Frontend@getAjax');





    
    
    
    
    
    
    

app/Services.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Services extends Model
{
    protected $table="services";
    
    use SoftDeletes;
    
     protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    
    protected $fillable = [
        'name',
        'description',
        'img',
        'created_at',
        'updated_at',
        'deleted_at'
        
        ];
        
    public function getImageAttribute($img){
        
        return asset($img);
        
    }    
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyServicesRequest;
use App\Http\Requests\StoreServicesRequest;
use App\Http\Requests\UpdateServicesRequest;
use App\Services;

class ServiceController extends Controller
{
   
    public function index()
    {
        abort_unless(\Gate::allows('service_access'), 403);

        $services = Services::all();

        return view('admin.services.index', compact('services'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('service_create'), 403);

        return view('admin.services.create');
    }


    public function store(StoreServicesRequest $request)
    {
        abort_unless(\Gate::allows('service_create'), 403);
        
        $image = $request->file('img');
        $image_new_name = time().$image->getClientOriginalName();
        $image->move(public_path() . '/uploads/services/',$image_new_name);
        
        $service = Services::create([
               'name'=>$request->name,
               'description'=>$request->description,
               'img'=>$image_new_name,
            
            ]);

        return redirect()->route('admin.services.index');
    }

    public function show(Services $service)
    {
        abort_unless(\Gate::allows('service_show'), 403);

        return view('admin.services.show', compact('service'));
    }
    
    public function edit(Services $service)
    {
        abort_unless(\Gate::allows('service_edit'), 403);

        return view('admin.services.edit', compact('service'));
    }

    public function update(UpdateServicesRequest $request, Services $service)
    {
        abort_unless(\Gate::allows('service_edit'), 403);
        
        if($request->hasFile('img')){
        $image = $request->file('img');
        $image_new_name = time().$image->getClientOriginalName();
        $image->move(public_path() . '/uploads/services/',$image_new_name);
        $service->img = $image_new_name;
        }
        
        $service->update([
            $service->name=$request->name,
            $service->description=$request->description,
            
        ]);
        
        $service->save();
        return redirect()->route('admin.services.index');
    }

    public function destroy(Services $service)
    {
        abort_unless(\Gate::allows('service_delete'), 403);

        $service->delete();

        return back();
    }

    public function massDestroy(MassDestroyServicesRequest $request)
    {
        Services::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }

}

resources/views/admin/services/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.service.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.services.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.service.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($service) ? $service->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.service.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                <label for="description">{{ trans('global.service.fields.description') }}</label>
                <textarea id="description" name="description" class="form-control">{{ old('description', isset($service) ? $service->description : '') }}</textarea>
                @if($errors->has('description'))
                    <em class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.service.fields.description_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('img') ? 'has-error' : '' }}">
                <label for="img">{{ trans('global.service.fields.img') }}</label>
                <input type="file" id="img" name="img" class="form-control" value="{{ old('img', isset($service) ? $service->img : '') }}">
                @if($errors->has('img'))
                    <em class="invalid-feedback">
                        {{ $errors->first('img') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.service.fields.img_helper') }}
                </p>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/services/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.service.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.services.update", [$service->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                <label for="name">{{ trans('global.service.fields.name') }}*</label>
                <input type="text" id="name" name="name" class="form-control" value="{{ old('name', isset($service) ? $service->name : '') }}">
                @if($errors->has('name'))
                    <em class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.service.fields.name_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('description') ? 'has-error' : '' }}">
                <label for="description">{{ trans('global.service.fields.description') }}</label>
                <textarea id="description" name="description" class="form-control ">{{ old('description', isset($service) ? $service->description : '') }}</textarea>
                @if($errors->has('description'))
                    <em class="invalid-feedback">
                        {{ $errors->first('description') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.service.fields.description_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('img') ? 'has-error' : '' }}">
                <label for="img">{{ trans('global.service.fields.img') }}</label>
                <input type="file" id="img" name="img" class="form-control" value="{{ old('img', isset($service) ? $service->img : '') }}">
                @if($errors->has('img'))
                    <em class="invalid-feedback">
                        {{ $errors->first('img') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.service.fields.img_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.admin')
@section('content')
@can('service_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.services.create") }}">
                {{ trans('global.add') }} {{ trans('global.service.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('global.service.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('global.service.fields.name') }}
                        </th>
                        <th>
                            {{ trans('global.service.fields.description') }}
                        </th>

                        <th>
                            {{ trans('global.service.fields.img') }}
                        </th>
                        
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($services as $key => $service)
                        <tr data-entry-id="{{ $service->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $service->name ?? '' }}
                            </td>
                            <td>
                                {{ $service->description ?? '' }}
                            </td>
                            <td>
                               <img src="{{ asset ('public/uploads/services/'.$service->img) }}" width="50" alt=" {{ trans('global.service.title_singular') }}"> 
                            </td>
                            <td>
                                @can('service_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.services.show', $service->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('service_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.services.edit', $service->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('service_delete')
                                    <form action="{{ route('admin.services.destroy', $service->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.services.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('service_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

resources/views/admin/services/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.service.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.service.fields.name') }}
                    </th>
                    <td>
                        {{ $service->name }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.service.fields.description') }}
                    </th>
                    <td>
                        {!! $service->description !!}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.service.fields.img') }}
                    </th>
                    <td>
                         {{ $service->img }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection