routes/web.php
<?php


    Route::get('/', 'Frontend@index');
    Route::redirect('/home', '/admin');

    Auth::routes(['register' => false]);

    Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    

    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');

    Route::resource('permissions', 'PermissionsController');

    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');

    Route::resource('users', 'UsersController');

    Route::delete('products/destroy', 'ProductsController@massDestroy')->name('products.massDestroy');

    Route::resource('products', 'ProductsController');

    Route::delete('blogs/destroy', 'BlogController@massDestroy')->name('blogs.massDestroy');

    Route::resource('blogs', 'BlogController');
    
    
    Route::delete('services/destroy', 'ServiceController@massDestroy')->name('services.massDestroy');

    Route::resource('services', 'ServiceController');
    
    
    Route::delete('projects/destroy', 'projectsController@massDestroy')->name('projects.massDestroy');

    Route::resource('projects', 'projectsController');





    Route::delete('faqs/destroy', 'faqController@massDestroy')->name('faqs.massDestroy');

    Route::resource('faqs', 'faqController');
    
    Route::delete('abouts/destroy', 'AboutController@massDestroy')->name('abouts.massDestroy');
    Route::resource('abouts', 'AboutController');
    
    Route::delete('phases/destroy', 'phasesController@massDestroy')->name('phases.massDestroy');
    Route::resource('phases', 'phasesController');
    
    Route::delete('contactus/destroy', 'ContactUsController@massDestroy')->name('contactuses.massDestroy');
    Route::resource('contactus', 'ContactUsController');
    
    Route::delete('settings/destroy', 'settingController@massDestroy')->name('settings.massDestroy');
    Route::resource('settings', 'settingController');


});

    Route::get('about', 'Frontend@about')->name('about');
    Route::get('blog', 'Frontend@blog')->name('blog');
    Route::get('blog-list/{id}', 'Frontend@blog_list');
    Route::get('contact', 'Frontend@contact');
    Route::get('faq', 'Frontend@faq');   
    Route::post('faq','Frontend@faqs')->name('fs');
    Route::get('service-details/{id}', 'Frontend@service_detail');
    Route::get('service', 'Frontend@service');

    Route::get('projects', 'Frontend@projects');

    Route::get('phases', 'phasesController@index')->name('phases');
    Route::get('setting', 'Frontend@setting')->name('phases');
    Route::post('mail', 'Frontend@cont')->name('mail');
    Route::get('mail', 'Frontend@contactReturn');
    Route::get('details', 'detailscontroller@index');

Route::post('getall', 'Frontend@getAjax');





    
    
    
    
    
    
    

app/faqs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class faqs extends Model
{
     use SoftDeletes;
     
      protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    
     protected $fillable = [
        'question',
        'answer',
        'category',
        'created_at',
        'updated_at',
        'deleted_at'
    ];
    
}

app/Http/Controllers/Admin/faqController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyFaqRequest;
use App\Http\Requests\StoreFaqRequest;
use App\Http\Requests\UpdateFaqRequest;
use App\faqs;

class faqController extends Controller
{
    public function index()
    {
        abort_unless(\Gate::allows('faq_access'), 403);

        $faqs = faqs::all();

        return view('admin.faqs.index', compact('faqs'));
    }

    public function create()
    {
        abort_unless(\Gate::allows('faq_create'), 403);

        return view('admin.faqs.create');
    }


    public function store(StoreFaqRequest $request)
    {
        abort_unless(\Gate::allows('faq_create'), 403);

        $faq = faqs::create($request->all());

        return redirect()->route('admin.faqs.index');
    }

    public function show(faqs $faq)
    {
        abort_unless(\Gate::allows('faq_show'), 403);

        return view('admin.faqs.show', compact('faq'));
    }
    
    public function edit(faqs $faq)
    {
        abort_unless(\Gate::allows('faq_edit'), 403);

        return view('admin.faqs.edit', compact('faq'));
    }

    public function update(UpdateFaqRequest $request, faqs $faq)
    {
        abort_unless(\Gate::allows('faq_edit'), 403);

        $faq->update($request->all());

        return redirect()->route('admin.faqs.index');
    }

    public function destroy(faqs $faq)
    {
        abort_unless(\Gate::allows('faq_delete'), 403);

        $faq->delete();

        return back();
    }

    public function massDestroy(MassDestroyFaqRequest $request)
    {
        faqs::whereIn('id', request('ids'))->delete();

        return response(null, 204);
    }
}

resources/views/admin/faqs/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('global.faq.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.faqs.store") }}" method="POST" enctype="multipart/form-data">
            @csrf
            <div class="form-group {{ $errors->has('question') ? 'has-error' : '' }}">
                <label for="question">{{ trans('global.faq.fields.question') }}*</label>
                <input type="text" id="question" name="question" class="form-control" value="{{ old('question', isset($faq) ? $faq->question : '') }}">
                @if($errors->has('question'))
                    <em class="invalid-feedback">
                        {{ $errors->first('question') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.faq.fields.question_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('answer') ? 'has-error' : '' }}">
                <label for="answer">{{ trans('global.faq.fields.answer') }}*</label>
                <input type="text" id="answer" name="answer" class="form-control" value="{{ old('answer', isset($faq) ? $faq->answer : '') }}">
                @if($errors->has('answer'))
                    <em class="invalid-feedback">
                        {{ $errors->first('answer') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.faq.fields.answer_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('category') ? 'has-error' : '' }}">
                <label for="category">{{ trans('global.faq.fields.category') }}*</label>
                <input type="text" id="category" name="category" class="form-control" value="{{ old('category', isset($faq) ? $faq->category : '') }}">
                @if($errors->has('category'))
                    <em class="invalid-feedback">
                        {{ $errors->first('category') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.faq.fields.category_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/faqs/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('global.faq.title_singular') }}
    </div>

    <div class="card-body">
        <form action="{{ route("admin.faqs.update", [$faq->id]) }}" method="POST" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <div class="form-group {{ $errors->has('question') ? 'has-error' : '' }}">
                <label for="question">{{ trans('global.faq.fields.question') }}*</label>
                <input type="text" id="question" name="question" class="form-control" value="{{ old('question', isset($faq) ? $faq->question : '') }}">
                @if($errors->has('question'))
                    <em class="invalid-feedback">
                        {{ $errors->first('question') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.faq.fields.question_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('answer') ? 'has-error' : '' }}">
                <label for="answer">{{ trans('global.faq.fields.answer') }}*</label>
                <input type="text" id="answer" name="answer" class="form-control" value="{{ old('answer', isset($faq) ? $faq->answer : '') }}">
                @if($errors->has('answer'))
                    <em class="invalid-feedback">
                        {{ $errors->first('answer') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.faq.fields.answer_helper') }}
                </p>
            </div>
            <div class="form-group {{ $errors->has('category') ? 'has-error' : '' }}">
                <label for="category">{{ trans('global.faq.fields.category') }}*</label>
                <input type="text" id="category" name="category" class="form-control" value="{{ old('category', isset($faq) ? $faq->category : '') }}">
                @if($errors->has('category'))
                    <em class="invalid-feedback">
                        {{ $errors->first('category') }}
                    </em>
                @endif
                <p class="helper-block">
                    {{ trans('global.faq.fields.category_helper') }}
                </p>
            </div>
            <div>
                <input class="btn btn-danger" type="submit" value="{{ trans('global.save') }}">
            </div>
        </form>
    </div>
</div>

@endsection

resources/views/admin/faqs/index.blade.php
@extends('layouts.admin')
@section('content')
@can('faq_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route("admin.faqs.create") }}">
                {{ trans('global.add') }} {{ trans('global.faq.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('global.faq.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('global.faq.fields.question') }}
                        </th>
                        <th>
                            {{ trans('global.faq.fields.answer') }}
                        </th>

                        <th>
                            {{ trans('global.faq.fields.category') }}
                        </th>
                        
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($faqs as $key => $faq)
                        <tr data-entry-id="{{ $faq->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $faq->question ?? '' }}
                            </td>
                            <td>
                                {{ $faq->answer ?? '' }}
                            </td>
                            <td>
                                 {{ $faq->category ?? '' }}
                            </td>
                            <td>
                                @can('faq_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.faqs.show', $faq->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan
                                @can('faq_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.faqs.edit', $faq->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan
                                @can('faq_delete')
                                    <form action="{{ route('admin.faqs.destroy', $faq->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan
                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@section('scripts')
@parent
<script>
    $(function () {
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.faqs.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('blog_delete')
  dtButtons.push(deleteButton)
@endcan

  $('.datatable:not(.ajaxTable)').DataTable({ buttons: dtButtons })
})

</script>
@endsection
@endsection

resources/views/admin/faqs/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('global.faq.title') }}
    </div>

    <div class="card-body">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th>
                        {{ trans('global.faq.fields.question') }}
                    </th>
                    <td>
                        {{ $faq->question }}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.faq.fields.answer') }}
                    </th>
                    <td>
                        {!! $faq->answer !!}
                    </td>
                </tr>
                <tr>
                    <th>
                        {{ trans('global.faq.fields.category') }}
                    </th>
                    <td>
                         {{ $faq->category }}
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection